# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb288c2f37cf939275a8233434332e8e273416cad31690ef303ddaa8c3d1cf8f4164edd55d6f8b688bd87c9a099cbabd98496f5e21a7ce41f038787e1137575b

test:
  secret_key_base: 7e6ede079fdad8aa96c8a80151ace15db052619f59d9f9804c1666b2ee413e32f54d568e7d548018ccc39e35ecf301b36d6dee726d26d25006e6c19c767d5bcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
